my: 
  propertyfile: 
    value: Welcome to Spring Boot from GitHub config 1
    listOfMovies: Raaz,Krish,Darr, From GitHub config 1
    mapOfmovies: "{Raaz: 'old movie', Krish: '2', Darr: 'Shahrukh movie'}"
    
db:
  connectionUrl: http://localdb:8090/githubconfig1
  username: admin_githubconfig1
  password: pass_githubconfig1
  hostname: localDB_githubconfig1
  
management.endpoints.web.exposure.include: hystrix.stream
eureka.instance.prefer-ip-address: true
