my: 
  propertyfile: 
    value: Welcome to Spring Boot
    listOfMovies: Raaz,Krish,Darr
    mapOfmovies: "{Raaz: 'old movie', Krish: '2', Darr: 'Shahrukh movie'}"
    
db:
  connectionUrl: http://localdb:8090/
  username: admin
  password: pass
  hostname: localDB
