server:
  port: 8081

spring:
  application: 
    name: MOVIECATALOGUESERVICE
    
my: 
  propertyfile: 
    value1: Welcome to Spring Boot from MovieCatalogService.yml GitHub repo
    specificProp: This property is only present in MovieCatalogService.yml GitHub repo and updated today2.
