server:
  port: 8081

spring:
  application: 
    name: MOVIECATALOGUESERVICE
    
my: 
  propertyfile: 
    value: Welcome to Spring Boot from MovieCatalogService.yml GitHub repo
    specificProp: This property is onlu present in MovieCatalogService.yml GitHub repo
